# Generated by Django 5.0.6 on 2024-06-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
