# Generated by Django 5.0.6 on 2024-06-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_image_alter_product_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='regionId',
            new_name='region',
        ),
    ]
